import type { Metadata } from 'next';
import {  Montserrat } from 'next/font/google';
import './globals.css'
import { AppRouterCacheProvider } from '@mui/material-nextjs/build/v14-appRouter';
import Navbar from './components/Navbar'


const montserrat = Montserrat({
   weight: ["400", "500", "600", "700", "800", "900"],
   subsets: ['latin'] 
  })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={montserrat.className}  suppressHydrationWarning={true}>
        <AppRouterCacheProvider> 
          <Navbar/>
          {children}
          </AppRouterCacheProvider>
      </body>
    </html>
  )
}
// https://picsum.photos/200